CREATE DATABASE LOJA;

CREATE TABLE CATEGORIAS(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT,
	TITULO VARCHAR(100) NOT NULL
);
--INSERT INTO categorias (TITULO)VALUES('Sapatos'),('Camisas'),('Calças'),('Bonés')

CREATE TABLE PRODUTOS(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    ID_CATEGORIA INT(11) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    IMAGEM VARCHAR(36) NOT NULL,
    PRECO FLOAT NOT NULL,
    QUANTIDADE INT(11) NOT NULL,
    DESCRICAO TEXT NOT NULL
);

CREATE TABLE VENDAS(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT(11) NOT NULL,
    ID_PRODUTO INT(11) NOT NULL,
    QUANTIDADE INT(11) NOT NULL,
    ENDERECO TEXT NOT NULL,
    VALOR FLOAT NOT NULL,
    FORMA_PG INT(11) NOT NULL
)

CREATE TABLE PAGAMENTOS(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL
);
-- INSERT INTO pagamentos (NOME)VALUES ('Grátis'), ('Pagseguro'),('Paypal'), ('Boleto'), ('MoIP')